In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\rithi\Desktop\GEN_AI\fake_news_detection\src\liar_data\csv file\train.csv")
df

id        label  \
0       2635.json        false   
1      10540.json    half-true   
2        324.json  mostly-true   
3       1123.json        false   
4       9028.json    half-true   
...           ...          ...   
10233   5473.json  mostly-true   
10234   3408.json  mostly-true   
10235   3959.json    half-true   
10236   2253.json        false   
10237   1155.json   pants-fire   

                                               statement  \
0      Says the Annies List political group supports ...   
1      When did the decline of coal start? It started...   
2      Hillary Clinton agrees with John McCain "by vo...   
3      Health care reform legislation is likely to ma...   
4      The economic turnaround started at the end of ...   
...                                                  ...   
10233  There are a larger number of shark attacks in ...   
10234  Democrats have now become the party of the [At...   
10235  Says an alternative to Social Security that op...   
10236  On lifting the U.S. Cuban embargo and allowing...   
10237  The Department of Veterans Affairs has a manua...   

                                  subject         speaker  \
0                                abortion    dwayne-bohac   
1      energy,history,job-accomplishments  scott-surovell   
2                          foreign-policy    barack-obama   
3                             health-care    blog-posting   
4                            economy,jobs   charlie-crist   
...                                   ...             ...   
10233                   animals,elections    aclu-florida   
10234                           elections     alan-powell   
10235          retirement,social-security     herman-cain   
10236              florida,foreign-policy     jeff-greene   
10237                health-care,veterans  michael-steele   

                                           job_title state_info  \
0                               State representative      Texas   
1                                     State delegate   Virginia   
2                                          President   Illinois   
3                                                NaN        NaN   
4                                                NaN    Florida   
...                                              ...        ...   
10233                                            NaN    Florida   
10234                                            NaN    Georgia   
10235                                            NaN    Georgia   
10236                                            NaN    Florida   
10237  chairman of the Republican National Committee   Maryland   

      party_affiliation  barely_true_counts  false_counts  half_true_counts  \
0            republican                   0             1                 0   
1              democrat                   0             0                 1   
2              democrat                  70            71               160   
3                  none                   7            19                 3   
4              democrat                  15             9                20   
...                 ...                 ...           ...               ...   
10233              none                   0             1                 1   
10234        republican                   0             0                 0   
10235        republican                   4            11                 5   
10236          democrat                   3             1                 3   
10237        republican                   0             1                 1   

       mostly_true_counts  pants_on_fire_counts  \
0                       0                     0   
1                       1                     0   
2                     163                     9   
3                       5                    44   
4                      19                     2   
...                   ...                   ...   
10233                   1                

In [3]:
df["job_title"].value_counts()

President                                        492
U.S. Senator                                     479
Governor                                         391
President-Elect                                  273
U.S. senator                                     263
                                                ... 
Pundit and communications consultant               1
Harrisonburg city councilman                       1
Theme park company                                 1
Executive director, NARAL Pro-Choice Virginia      1
President, The Whitman Strategy Group              1
Name: job_title, Length: 1184, dtype: int64

In [4]:
df["state_info"].value_counts()

Texas             1009
Florida            997
Wisconsin          713
New York           657
Illinois           556
                  ... 
Qatar                1
Virginia             1
United Kingdom       1
China                1
Rhode Island         1
Name: state_info, Length: 84, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10238 entries, 0 to 10237
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    10238 non-null  object
 1   label                 10238 non-null  object
 2   statement             10238 non-null  object
 3   subject               10238 non-null  object
 4   speaker               10238 non-null  object
 5   job_title             7343 non-null   object
 6   state_info            8032 non-null   object
 7   party_affiliation     10238 non-null  object
 8   barely_true_counts    10238 non-null  int64 
 9   false_counts          10238 non-null  int64 
 10  half_true_counts      10238 non-null  int64 
 11  mostly_true_counts    10238 non-null  int64 
 12  pants_on_fire_counts  10238 non-null  int64 
 13  context               10138 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.1+ MB


In [6]:
df.describe()

barely_true_counts  false_counts  half_true_counts  mostly_true_counts  \
count        10238.000000  10238.000000      10238.000000        10238.000000   
mean            11.533210     13.286482         17.133718           16.434265   
std             18.973764     24.112936         35.846511           36.151688   
min              0.000000      0.000000          0.000000            0.000000   
25%              0.000000      0.000000          0.000000            0.000000   
50%              2.000000      2.000000          3.000000            3.000000   
75%             12.000000     12.000000         13.000000           11.000000   
max             70.000000    114.000000        160.000000          163.000000   

       pants_on_fire_counts  
count          10238.000000  
mean               6.201407  
std               16.128927  
min                0.000000  
25%                0.000000  
50%                1.000000  
75%                5.000000  
max              105.000000

In [7]:
df.isnull().sum()

id                         0
label                      0
statement                  0
subject                    0
speaker                    0
job_title               2895
state_info              2206
party_affiliation          0
barely_true_counts         0
false_counts               0
half_true_counts           0
mostly_true_counts         0
pants_on_fire_counts       0
context                  100
dtype: int64

In [8]:
x = df.drop("label", axis=1)
y = df["label"]


In [9]:
for col in df.columns:
    df[col].fillna(df[col].mode()[0], inplace=True)


In [10]:
df.isnull().sum()

id                      0
label                   0
statement               0
subject                 0
speaker                 0
job_title               0
state_info              0
party_affiliation       0
barely_true_counts      0
false_counts            0
half_true_counts        0
mostly_true_counts      0
pants_on_fire_counts    0
context                 0
dtype: int64

In [11]:
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler, LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from scipy.sparse import hstack


df.drop("id", axis=1, inplace=True)

label_order = {'pants-fire': 0, 'false': 1, 'barely-true': 2, 'half-true': 3, 'mostly-true': 4, 'true': 5}
df['label'] = df['label'].map(label_order)

statement_tfidf = TfidfVectorizer(max_features=70)
X_statement = statement_tfidf.fit_transform(df['statement'])

df['subject'] = df['subject'].apply(lambda x: x.split(','))
all_subjects = pd.Series([s for sublist in df['subject'] for s in sublist])
top_subjects = all_subjects.value_counts().nlargest(10).index
df['subject'] = df['subject'].apply(lambda lst: [s for s in lst if s in top_subjects])
mlb = MultiLabelBinarizer(classes=top_subjects)
X_subject = mlb.fit_transform(df['subject'])

for col in ['speaker', 'state_info']:
    freq_map = df[col].value_counts().to_dict()
    df[col + '_freq'] = df[col].map(freq_map)

job_tfidf = TfidfVectorizer(max_features=10)
X_job = job_tfidf.fit_transform(df['job_title'])

le = LabelEncoder()
df["party_affiliation"] = le.fit_transform(df["party_affiliation"].astype(str))

count_cols = ['barely_true_counts', 'false_counts', 'half_true_counts', 'mostly_true_counts', 'pants_on_fire_counts']
scaler = StandardScaler()
df[count_cols] = scaler.fit_transform(df[count_cols])

context_tfidf = TfidfVectorizer(max_features=10)
X_context = context_tfidf.fit_transform(df['context'])

X_final = hstack([X_statement, X_subject, X_job, X_context])
X_final_dense = pd.DataFrame(X_final.toarray())

final_df = pd.concat([X_final_dense,
                      df[['speaker_freq', 'state_info_freq']],
                      df[count_cols],
                      df[["party_affiliation"]]
                     ], axis=1)

y = df['label']



In [12]:
X_final_dense

0    1    2         3         4         5    6         7    8    9   \
0      0.0  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.0   
1      0.0  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.0   
2      0.0  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.0   
3      0.0  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.000000  0.0  0.0   
4      0.0  0.0  0.0  0.000000  0.000000  0.000000  0.0  0.739506  0.0  0.0   
...    ...  ...  ...       ...       ...       ...  ...       ...  ...  ...   
10233  0.0  0.0  0.0  0.000000  0.000000  0.536420  0.0  0.000000  0.0  0.0   
10234  0.0  0.0  0.0  0.000000  0.379139  0.000000  0.0  0.000000  0.0  0.0   
10235  0.0  0.0  0.0  0.315536  0.000000  0.000000  0.0  0.000000  0.0  0.0   
10236  0.0  0.0  0.0  0.000000  0.524703  0.000000  0.0  0.000000  0.0  0.0   
10237  0.0  0.0  0.0  0.000000  0.000000  0.244611  0.0  0.000000  0.0  0.0   

       ...   90        91   92        93   94        95       96        97  \
0      ...  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.00000  0.000000   
1      ...  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.00000  0.000000   
2      ...  0.0  0.000000  0.0  0.000000  0.0  0.000000  0.00000  0.000000   
3      ...  0.0  0.000000  0.0  0.000000  0.0  0.000000  1.00000  0.000000   
4      ...  0.0  0.549668  0.0  0.000000  0.0  0.589720  0.00000  0.591688   
...    ...  ...       ...  ...       ...  ...       ...      ...       ...   
10233  ...  0.0  0.000000  0.0  0.000000  0.0  0.576229  0.00000  0.578151   
10234  ...  0.0  0.681829  0.0  0.000000  0.0  0.731512  0.00000  0.000000   
10235  ...  0.0  0.000000  0.0  1.000000  0.0  0.000000  0.00000  0.000000   
10236  ...  0.0  0.000000  0.0  0.790255  0.0  0.000000  0.00000  0.612778   
10237  ...  0.0  0.000000  0.0  0.000000  0.0  0.636884  0.77096  0.000000   

        98        99  
0      0.0  0.000000  
1      1.0  0.000000  
2      0.0  0.000000  
3      0.0  0.000000  
4      0.0  0.000000  
...    ...       ...  
10233  0.0  0.577669  
10234  0.0  0.000000  
10235  0.0  0.000000  
10236  0.0  0.000000  
10237  0.0  0.000000  

[10238 rows x 100 columns]

In [13]:
y

0        1
1        3
2        4
3        1
4        3
        ..
10233    4
10234    4
10235    3
10236    1
10237    0
Name: label, Length: 10238, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Split into train+val and test
X_temp, X_test, y_temp, y_test = train_test_split(X_final_dense, y, test_size=0.2, random_state=42)

# Step 2: Split train+val into train and val (e.g., 60% train, 20% val, 20% test)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42)

# Step 3: Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

y_train_pred_dt = dt_model.predict(X_train)
y_val_pred_dt = dt_model.predict(X_val)
y_test_pred_dt = dt_model.predict(X_test)

print("🔹 Decision Tree")
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_dt))
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred_dt))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred_dt))
print("Classification Report (Test):\n", classification_report(y_test, y_test_pred_dt))
print("Confusion Matrix (Test):\n", confusion_matrix(y_test, y_test_pred_dt))


# Step 4: Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_train_pred_rf = rf_model.predict(X_train)
y_val_pred_rf = rf_model.predict(X_val)
y_test_pred_rf = rf_model.predict(X_test)

print("\n🔹 Random Forest")
print("Train Accuracy:", accuracy_score(y_train, y_train_pred_rf))
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred_rf))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred_rf))
print("Classification Report (Test):\n", classification_report(y_test, y_test_pred_rf))
print("Confusion Matrix (Test):\n", confusion_matrix(y_test, y_test_pred_rf))


🔹 Decision Tree
Train Accuracy: 0.9993487463366981
Validation Accuracy: 0.18603515625
Test Accuracy: 0.2060546875
Classification Report (Test):
               precision    recall  f1-score   support

           0       0.09      0.12      0.10       138
           1       0.21      0.23      0.22       364
           2       0.20      0.16      0.18       360
           3       0.23      0.22      0.22       450
           4       0.24      0.22      0.23       405
           5       0.20      0.22      0.21       331

    accuracy                           0.21      2048
   macro avg       0.20      0.20      0.19      2048
weighted avg       0.21      0.21      0.21      2048

Confusion Matrix (Test):
 [[ 16  32  24  33  17  16]
 [ 30  84  48  78  66  58]
 [ 30  71  57  84  57  61]
 [ 38  80  61 100  92  79]
 [ 35  61  56  81  91  81]
 [ 29  69  37  68  54  74]]

🔹 Random Forest
Train Accuracy: 0.9993487463366981
Validation Accuracy: 0.2177734375
Test Accuracy: 0.22607421875
Classifi

In [ ]:
#final model
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.utils.class_weight import compute_sample_weight
from xgboost import XGBClassifier

# Load data
df = pd.read_csv(r"C:\Users\rithi\Desktop\GEN_AI\fake_news_detection\src\liar_data\csv file\train.csv")

# Fill missing categorical values with mode
categorical_cols = ["speaker", "job_title", "state_info", "party_affiliation", "context"]
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Drop ID column
if "id" in df.columns:
    df.drop(columns=["id"], inplace=True)

# Normalize label values
df["label"] = df["label"].astype(str).str.lower().str.strip()

# Convert labels to binary
def simplify_label(label):
    label_map = {
        "pants-fire": 0,
        "false": 0,
        "barely-true": 0,
        "half-true": 0,
        "mostly-true": 1,
        "true": 1
    }
    return label_map.get(label, -1)

df["label"] = df["label"].apply(simplify_label)
df = df[df["label"] != -1]

# Combine text fields
df["text"] = df["statement"].fillna('') + " " + df["context"].fillna('') + " " + df["job_title"].fillna('')

# TF-IDF vectorization
tfidf = TfidfVectorizer(max_features=5000)
X_tfidf = tfidf.fit_transform(df["text"])

# Dimensionality reduction
svd = TruncatedSVD(n_components=100, random_state=42)
X_svd = svd.fit_transform(X_tfidf)

# Encode categorical features
encoded_cols = []
for col in ['speaker', 'state_info', 'party_affiliation']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoded_cols.append(col)

# Numeric features
count_cols = ['barely_true_counts', 'false_counts', 'half_true_counts',
              'mostly_true_counts', 'pants_on_fire_counts']
X_numeric = df[count_cols + encoded_cols].astype(float).values

# Final feature matrix and labels
X_final = np.hstack([X_svd, X_numeric])
y = df["label"]

# Train/Validation/Test split
X_temp, X_test, y_temp, y_test = train_test_split(X_final, y, test_size=0.2, stratify=y, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, stratify=y_temp, random_state=42)

# Handle imbalance
sample_weights = compute_sample_weight(class_weight="balanced", y=y_train)

# Train XGBoost
model = XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    learning_rate=0.1,
    max_depth=6,
    n_estimators=200,
    subsample=0.8,
    colsample_bytree=0.8,
    use_label_encoder=False,
    random_state=42
)
model.fit(X_train, y_train, sample_weight=sample_weights)

# Define evaluation
def evaluate(name, y_true, y_pred):
    print(f"\n🔹 {name} Set")
    print("Accuracy:", accuracy_score(y_true, y_pred))
    print("F1 Score:", f1_score(y_true, y_pred))
    print("Classification Report:\n", classification_report(y_true, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

# Predict without threshold
y_pred_train = model.predict(X_train)
y_pred_val = model.predict(X_val)
y_pred_test = model.predict(X_test)

# Evaluate normal predictions
evaluate("Train", y_train, y_pred_train)
evaluate("Validation", y_val, y_pred_val)
evaluate("Test", y_test, y_pred_test)

# 🔻 Threshold tuning
y_probs_test = model.predict_proba(X_test)[:, 1]  # Probabilities for class 1
y_pred_thresh_test = (y_probs_test >= 0.4).astype(int)  # Adjust threshold here (e.g., 0.4)

# Evaluate with threshold tuning
evaluate("Test (Threshold=0.4)", y_test, y_pred_thresh_test)



🔹 Train Set
Accuracy: 0.9990877101524828
F1 Score: 0.9987068169222243
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      4969
           1       1.00      1.00      1.00      2704

    accuracy                           1.00      7673
   macro avg       1.00      1.00      1.00      7673
weighted avg       1.00      1.00      1.00      7673

Confusion Matrix:
 [[4963    6]
 [   1 2703]]

🔹 Validation Set
Accuracy: 0.7212666145426114
F1 Score: 0.5847408270238789
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.81      0.79      1656
           1       0.62      0.56      0.58       902

    accuracy                           0.72      2558
   macro avg       0.69      0.68      0.69      2558
weighted avg       0.72      0.72      0.72      2558

Confusion Matrix:
 [[1343  313]
 [ 400  502]]

🔹 Test Set
Accuracy: 0.7333854573885848
F1 Score: 0.602100

In [24]:
from sklearn.metrics import f1_score

best_thresh = 0.5
best_f1 = 0

for t in np.arange(0.1, 0.9, 0.05):
    preds = (y_probs_test >= t).astype(int)
    score = f1_score(y_test, preds)
    if score > best_f1:
        best_f1 = score
        best_thresh = t

print("Best Threshold:", best_thresh)
print("Best F1 Score:", best_f1)


Best Threshold: 0.3500000000000001
Best F1 Score: 0.6284337349397591


In [25]:
# Use best threshold
final_thresh = 0.35
y_pred_thresh_test = (y_probs_test >= final_thresh).astype(int)

evaluate("Test (Threshold=0.35)", y_test, y_pred_thresh_test)



🔹 Test (Threshold=0.35) Set
Accuracy: 0.6985926505082095
F1 Score: 0.6284337349397591
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.68      0.75      1657
           1       0.56      0.72      0.63       901

    accuracy                           0.70      2558
   macro avg       0.69      0.70      0.69      2558
weighted avg       0.73      0.70      0.70      2558

Confusion Matrix:
 [[1135  522]
 [ 249  652]]
